// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/28/2026, 10:37:11 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["E:/lombas/frontend/admin-dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/lombas/frontend/admin-dashboard/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/lombas/frontend/admin-dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/lombas/frontend/admin-dashboard/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/lombas/frontend/admin-dashboard/plugins/**/*.{js,ts,mjs}","E:/lombas/frontend/admin-dashboard/composables/**/*.{js,ts,mjs}","E:/lombas/frontend/admin-dashboard/utils/**/*.{js,ts,mjs}","E:/lombas/frontend/admin-dashboard/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/lombas/frontend/admin-dashboard/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/lombas/frontend/admin-dashboard/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/lombas/frontend/admin-dashboard/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;